[package]
name = "sortify"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
spotify-rs = { path = "spotify-rs" }
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
